---
title: "bar_brief_discussion"
author: "Aiden Dickson"
date: "5/11/2021"
output: html_document
---
<head>
<style>

p.y{
  font-family: arial;
  font-size: 15px;
  color: #003366;
}

div.relbar {
  position: relative;
  top: 155px;
  right: 300px;
  width: 800px;
  height: 100px;
} 

div.absolbar {
  position: absolute;
  top: 140px;
  right: 60px;
  width: 900px;
  height: 90px;
  overflow-wrap: break-word;
  
}
</style>
</head>

<body>

<div class= "absolbar">
    <p class="y">
      The dataset depicted below on 'Plot tab' and 'Table tab' (and in Scatter-plot format next tab) is the result of a survey of all ages of participant who earned a bachelor's degree in the labeled majors. On 'Plot tab' select the 'Y' variable statistics within each Major: 'Total' for 'Total Bachelors' View, 'Employed' for how many 'Employed', 'Employed Full Time Year Round' or 'Unemployed' for how many fit this description at time of survey, 'Unemployment Rate' for the ratio per Major, Median for the Median Earnings, or Percentile 25th or 75th, for the average income level in these respective eschelons, per major at the time of survey.</p>
      
</div>

</body>