---
title: "scatter_brief_discussion"
author: "Aiden Dickson"
date: "5/11/2021"
output: html_document
---
<head>
<style>

p.a{
  font-family: arial;
  font-size: 16px;
  color: #003366;
}

div.relscatter {
  position: relative;
  top: 100px;
  right: 300px;
  width: 800px;
  height: 100px;
} 

div.absolscatter {
  position: absolute;
  top: 550px;
  left: 50px;
  width: 500px;
  height: 100px;
  overflow-wrap: break-word;
  
}
</style>
</head>

<body>

<div class= "absolscatter">
    <p class= "a">
      This plot will give a variable list comparison of the super-set categories of major to get an overall view of where Computer Science and Mathematics stand in reference. Small caveat that this scatter plot will also allow the user to select what is impossible to depict clearly and will still make an attempt, eg trying to squeeze all categories of Major on the y-axis.  A good rule of thumb for use is to select categorical variables for the x axis (eg Major) and numerical values on a continuum, on the y (eg Median Income). *Majors were intentionally removed because all could not be represented if sample size increased.</p>
      
</div>

</body>